# -*- coding: utf-8 -*-
"""ML_ Iris Flower Classification .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WdoM-CW3t5Xt0xnJBKM5X8J9HMbEAKCj
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the Iris dataset
iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data['species'] = iris.target

# Data exploration
print(data.describe())
print(data['species'].value_counts())

# Data visualization
sns.pairplot(data, hue='species', markers=["o", "s", "D"])
plt.show()

# Data preprocessing
X = data.drop('species', axis=1)
y = data['species']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model building
model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Model evaluation
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

